### 0) signup
POST {{host}}/api/v1/users/signup
Content-Type: application/json

{
  "loginId": "devlog112",
  "password": "Password!234",
  "nickname": "테스트1",
  "email": "devlog1112@devlog.com"
}

### 1) login
POST {{host}}/api/v1/users/login
Content-Type: application/json

{
  "loginId": "devlog112",
  "password": "Password!234"
}

### 2) me (access 필요)
GET {{host}}/api/v1/users/me
Authorization: Bearer {{accessToken}}

### 3) reissue (refresh로 access 재발급)
POST {{host}}/api/v1/users/reissue
Content-Type: application/json

{
  "refreshToken": "{{refreshToken}}"
}

### 4) me with NEW access
GET {{host}}/api/v1/users/me
Authorization: Bearer {{newAccessToken}}

### 5) logout (refresh 삭제)
POST {{host}}/api/v1/users/logout
Authorization: Bearer {{accessToken}}

### 6) reissue after logout (should fail)
POST {{host}}/api/v1/users/reissue
Content-Type: application/json

{
  "refreshToken": "{{refreshToken}}"
}

### Post 생성
POST {{host}}/api/v1/posts
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "title": "두 번째 게시글",
  "content": "Day6 Post 생성 테스트2"
}

### Post 단건 조회
GET {{host}}/api/v1/posts/2
Authorization: Bearer {{accessToken}}

### Post 목록 조회
GET {{host}}/api/v1/posts
Authorization: Bearer {{accessToken}}

### Post 수정 (작성자)
PUT {{host}}/api/v1/posts/4
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "title": "수정된 제목",
  "content": "수정된 내용"
}

### Post 삭제 (작성자)
DELETE {{host}}/api/v1/posts/4
Authorization: Bearer {{accessToken}}
